name: randomnumber

on:
  release:
    types: [published]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{github.event.release.tag_name}}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: aungnyikhaing1629/randomnumber:${{github.event.release.tag_name}}

      - 
        name: Send custom JSON data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.18.0
        with:
          # For posting a rich message using Block Kit
          payload: |
          {
            "text": "Name:Aung Nyi Khaing\nMatriculation:abc123\nEmail:aungnyikhaing94@gmail.com\nRepo:git://github.com:aungnyikhaing94/randomnumber.git\nImage name:aungnyikhaing1629/randomnumber:${{github.event.release.tag_name}}\nImage url:https://hub.docker.com/repository/docker/aungnyikhaing1629/randomnumber"
          }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK